# Generated by Django 3.2.4 on 2021-06-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('contractor_name', models.CharField(max_length=250)),
                ('pipe_type', models.CharField(max_length=50)),
                ('pipe_size', models.IntegerField()),
                ('done_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('result_1', models.IntegerField()),
                ('result_2', models.IntegerField()),
                ('result_3', models.IntegerField(blank=True, null=True)),
                ('result_4', models.IntegerField(blank=True, null=True)),
                ('result_5', models.IntegerField(blank=True, null=True)),
                ('result_6', models.IntegerField(blank=True, null=True)),
                ('result_7', models.IntegerField(blank=True, null=True)),
                ('result_8', models.IntegerField(blank=True, null=True)),
                ('result_9', models.IntegerField(blank=True, null=True)),
                ('result_10', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['done_on'],
            },
        ),
    ]
